services:
  recon-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        WAYBACKURLS_VERSION: "v0.1.0"
        KATANA_VERSION: "v1.7.0"
        PARAMETH_COMMIT: "8da6f27c071f00bc0bd26a565de474e7ab5baa42"
    image: local/hermes-recon-web:0.1

  recon-nuclei:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nuclei
      args:
        NUCLEI_VERSION: "3.11.1"
        NUCLEI_TEMPLATES_VERSION: "10.4.7"
        NUCLEI_TEMPLATES_COMMIT: "83234ce456da3e90dda86dfbc5e605e64a846df3"
    image: local/hermes-recon-nuclei:0.1
