services:
  recon-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        KATANA_VERSION: "v1.7.0"
    image: local/hermes-recon-web:0.2

  recon-nuclei:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nuclei
      args:
        NUCLEI_VERSION: "3.11.1"
        NUCLEI_TEMPLATES_VERSION: "10.4.7"
        NUCLEI_TEMPLATES_COMMIT: "83234ce456da3e90dda86dfbc5e605e64a846df3"
    image: local/hermes-recon-nuclei:0.1
